### PR TITLE
update node version

### PR DESCRIPTION
**Pull request by DiegoFleitas**
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions

### CODE REVIEW

**Review by bsdkurt — CHANGES_REQUESTED** [review]
Hi Diego. Thanks for the pull request. There are several things in your pull request that I didn't want to merge so I went forward and just updated the nodejs runtime version. The intent of the example was to keep it as simple as possible and not have additional dependencies etc. The addition of dotenv is one of the things I was trying to avoid.

**Comment by bsdkurt** [comment]
I committed a simple update to the nodejs runtime and tested the steps outlined in the readme. It is working as intended now.

**Comment by DiegoFleitas** [comment]
> Hi Diego. Thanks for the pull request. There are several things in your pull request that I didn't want to merge so I went forward and just updated the nodejs runtime version. The intent of the example was to keep it as simple as possible and not have additional dependencies etc. The addition of dotenv is one of the things I was trying to avoid.

No problem! I intended my PR to be the first commit only but continued working on my dev branch (silly me) I should have created a specific branch for this. Good its working now! Have a good weekend 🍻

**Comment by bsdkurt** [comment]
> > Hi Diego. Thanks for the pull request. There are several things in your pull request that I didn't want to merge so I went forward and just updated the nodejs runtime version. The intent of the example was to keep it as simple as possible and not have additional dependencies etc. The addition of dotenv is one of the things I was trying to avoid.
> 
> No problem! I intended my PR to be the first commit only but continued working on my dev branch (silly me) I should have created a specific branch for this. Good its working now! Have a good weekend 🍻

Thanks for pointing out the issue. Have a good weekend too!

**Pull request closed without merging**
